version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-github-action
    container_name: node-github-action
    restart: always
    ports:
      - "3000:3000"
