name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up SSH connection
      uses: webfactory/ssh-agent@v0.5.2
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Rsync files
      run: |
        rsync -e "ssh -o StrictHostKeyChecking=no" -r --delete --exclude='.git*' ${{ github.workspace }}/ ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/root/node-github-actions
    - name: SSH into server and run Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'cd /root/node-github-actions && docker compose down && docker compose up --build -d'
      
    # - name: Install SSH
    #   run: sudo apt-get install openssh-client
    # - name: Deploy code
    #   run: rsync -r --delete-after -e "ssh -i ${{ secrets.SSH_PRIVATE_KEY }}" ${{ github.workspace }}/ ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/node-github-actions
    #   env:
    #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    # - name: SSH into server and run Docker Compose
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.SERVER_HOST }}
    #     username: ${{ secrets.SERVER_USERNAME }}
    #     key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     script: |
    #       cd /node-github-actions
    #       docker-compose down
    #       docker-compose up --build -d