name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up SSH connection
      uses: webfactory/ssh-agent@v0.5.2
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Rsync files
      run: |
        rsync -e "ssh -o StrictHostKeyChecking=no" -r --delete --exclude='.git*' ${{ github.workspace }}/ ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/root/node-github-actions
    - name: SSH into server and run commands
      run: |
         ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'cd /root/node-github-actions && docker build -t node-github-action:${{ github.ref }} . && docker compose down && docker compose up -d'